name: SonarQube Payments Analysis

on:
  push:
    branches:
      - main
    paths:
      - 'services/payments/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'services/payments/**'

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: services/payments/package-lock.json

      - name: Install dependencies
        working-directory: services/payments
        run: npm ci

      - name: Run tests and coverage
        working-directory: services/payments
        env:
          POSTGRES_DB: serveaso
        run: npm run test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: services/payments
